### ISSUE TITLE
Cannot npm install from npmjs.org

### ISSUE THREAD

**Issue by Munawwar** [AndreasMadsen/htmlparser-benchmark#2]
I get the following error message when I do a `npm install htmlparser-benchmark`:
```
npm http GET https://registry.npmjs.org/htmlparser-benchmark/-/htmlparser-benchmark-1.1.1.tgz
npm http 200 https://registry.npmjs.org/htmlparser-benchmark/-/htmlparser-benchmark-1.1.1.tgz
npm ERR! Error: shasum check failed for /home/myusername/tmp/npm-418-f_OTUDwS/registry.npmjs.org/htmlparser-benchmark/-/htmlparser-benchmark-1.1.1.tgz
npm ERR! Expected: fc353328b8dfcf5a58217bcc83086862f1713ee2
npm ERR! Actual:   436235f584d549eae1c2f8bd9365587d6ae1b801
npm ERR! From:     https://registry.npmjs.org/htmlparser-benchmark/-/htmlparser-benchmark-1.1.1.tgz
npm ERR!     at /home/myusername/.local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/home/myusername/.local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:929:16
npm ERR!     at process._tickCallback (node.js:419:13)
```
Note the "shasum check failed" error. Maybe the .tgz file uploaded is corrupted?

**Comment by AndreasMadsen** [comment]
I had no problem installing this (just tried). The tarball is quite big so if you are on an obscure connection I guess you could get a bad check sum. In any case there have been a few changes to the module, so I published a new version anyway.

**Comment by Munawwar** [comment]
Sorry for the false alarm then.
By the way, I am using this benchmark tool on (neutron-html5parser)[https://github.com/Munawwar/neutron-html5parser#benchmarking]. Thanks.

**Comment by AndreasMadsen** [comment]
No problem. You are welcome to make a PR adding you module to the benchmark suite.
