### ISSUE TITLE
Unable to benchmark a parser that returns a Promise

### ISSUE THREAD

**Issue by kshetline** [AndreasMadsen/htmlparser-benchmark#9]
I tried to benchmark an HTML parser I'm working on that returns a `Promise` for its results. This benchmark was unable to work with that parser, however, most likely because Node doesn't wait for unresolved `Promise`s, it just moves on and terminates if everything else besides those `Promise`s has completed.

I was able to get around that problem with these small changes:
```
Benchmark.prototype._file = function (item, done) {
	var self = this;

	fs.readFile(item.file, 'utf8', function (err, html) {
		if (err) return done(err);

		var tic = process.hrtime();
		var parserResult = self._parser(html, function (err) {
			var toc = process.hrtime(tic);

			if (err) {
				done(err, toc);
			} else {
				self.emit('progress', item.key);
				done(null, toc);
			}
		});

		if (parserResult instanceof Promise) {
			var keepAlive = setTimeout(function() {}, 1E9);
			parserResult.then(function() { clearTimeout(keepAlive); });
		}
	});
};
```
Now that I've got your benchmark working for me, however, I'm probably going to abandon the `Promise`-returning version of my parser since it turned out to be 10 times slower than my synchronous parser! Nevertheless, someone else might want this capability, so I thought I'd offer my changes as a suggestion. Please let me know if you're interested and would want to see these changes submitted as a pull request.

**Comment by AndreasMadsen** [comment]
Sorry. If there really is an issue, you should isolate it to not depend on any module and open an issue at https://github.com/nodejs/node.

> This benchmark was unable to work with that parser, however, most likely because Node doesn't wait for unresolved Promises, it just moves on and terminates if everything else besides those Promises has completed.

I highly doubt this is true. You can always use `util.callbackify` to turn a promise into a callback. Secondly, "wait for unresolved Promises" isn't really a thing. resolving promises happens without interrupts as resolves or rejects are scheduled as microtask, thus there is nothing to wait for. Of course the `resolve()` or `reject()` call themself, are waiting for something but that is unrelated to promises.
